/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestCheckoutRouteImport } from './routes/test-checkout'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as ProgramRouteImport } from './routes/program'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DiscordRouteImport } from './routes/discord'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FeaturesRiskRouteImport } from './routes/features.risk'
import { Route as FeaturesMentorshipRouteImport } from './routes/features.mentorship'
import { Route as FeaturesCurriculumRouteImport } from './routes/features.curriculum'
import { Route as FeaturesCommunityRouteImport } from './routes/features.community'
import { Route as BlogBreakoutStrategyRouteImport } from './routes/blog.breakout-strategy'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as ApiPublicEnrollApplicationIdRouteImport } from './routes/api/public/enroll.$applicationId'

const TestCheckoutRoute = TestCheckoutRouteImport.update({
  id: '/test-checkout',
  path: '/test-checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramRoute = ProgramRouteImport.update({
  id: '/program',
  path: '/program',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscordRoute = DiscordRouteImport.update({
  id: '/discord',
  path: '/discord',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRiskRoute = FeaturesRiskRouteImport.update({
  id: '/features/risk',
  path: '/features/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesMentorshipRoute = FeaturesMentorshipRouteImport.update({
  id: '/features/mentorship',
  path: '/features/mentorship',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesCurriculumRoute = FeaturesCurriculumRouteImport.update({
  id: '/features/curriculum',
  path: '/features/curriculum',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesCommunityRoute = FeaturesCommunityRouteImport.update({
  id: '/features/community',
  path: '/features/community',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogBreakoutStrategyRoute = BlogBreakoutStrategyRouteImport.update({
  id: '/blog/breakout-strategy',
  path: '/blog/breakout-strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicEnrollApplicationIdRoute =
  ApiPublicEnrollApplicationIdRouteImport.update({
    id: '/api/public/enroll/$applicationId',
    path: '/api/public/enroll/$applicationId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/discord': typeof DiscordRoute
  '/privacy': typeof PrivacyRoute
  '/program': typeof ProgramRoute
  '/refund': typeof RefundRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/success': typeof SuccessRoute
  '/terms': typeof TermsRoute
  '/test-checkout': typeof TestCheckoutRoute
  '/blog/breakout-strategy': typeof BlogBreakoutStrategyRoute
  '/features/community': typeof FeaturesCommunityRoute
  '/features/curriculum': typeof FeaturesCurriculumRoute
  '/features/mentorship': typeof FeaturesMentorshipRoute
  '/features/risk': typeof FeaturesRiskRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/enroll/$applicationId': typeof ApiPublicEnrollApplicationIdRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/discord': typeof DiscordRoute
  '/privacy': typeof PrivacyRoute
  '/program': typeof ProgramRoute
  '/refund': typeof RefundRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/success': typeof SuccessRoute
  '/terms': typeof TermsRoute
  '/test-checkout': typeof TestCheckoutRoute
  '/blog/breakout-strategy': typeof BlogBreakoutStrategyRoute
  '/features/community': typeof FeaturesCommunityRoute
  '/features/curriculum': typeof FeaturesCurriculumRoute
  '/features/mentorship': typeof FeaturesMentorshipRoute
  '/features/risk': typeof FeaturesRiskRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/enroll/$applicationId': typeof ApiPublicEnrollApplicationIdRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/discord': typeof DiscordRoute
  '/privacy': typeof PrivacyRoute
  '/program': typeof ProgramRoute
  '/refund': typeof RefundRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/success': typeof SuccessRoute
  '/terms': typeof TermsRoute
  '/test-checkout': typeof TestCheckoutRoute
  '/blog/breakout-strategy': typeof BlogBreakoutStrategyRoute
  '/features/community': typeof FeaturesCommunityRoute
  '/features/curriculum': typeof FeaturesCurriculumRoute
  '/features/mentorship': typeof FeaturesMentorshipRoute
  '/features/risk': typeof FeaturesRiskRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/enroll/$applicationId': typeof ApiPublicEnrollApplicationIdRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/apply'
    | '/auth'
    | '/dashboard'
    | '/discord'
    | '/privacy'
    | '/program'
    | '/refund'
    | '/sitemap.xml'
    | '/success'
    | '/terms'
    | '/test-checkout'
    | '/blog/breakout-strategy'
    | '/features/community'
    | '/features/curriculum'
    | '/features/mentorship'
    | '/features/risk'
    | '/api/public/stripe-webhook'
    | '/api/public/enroll/$applicationId'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/apply'
    | '/auth'
    | '/dashboard'
    | '/discord'
    | '/privacy'
    | '/program'
    | '/refund'
    | '/sitemap.xml'
    | '/success'
    | '/terms'
    | '/test-checkout'
    | '/blog/breakout-strategy'
    | '/features/community'
    | '/features/curriculum'
    | '/features/mentorship'
    | '/features/risk'
    | '/api/public/stripe-webhook'
    | '/api/public/enroll/$applicationId'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/apply'
    | '/auth'
    | '/dashboard'
    | '/discord'
    | '/privacy'
    | '/program'
    | '/refund'
    | '/sitemap.xml'
    | '/success'
    | '/terms'
    | '/test-checkout'
    | '/blog/breakout-strategy'
    | '/features/community'
    | '/features/curriculum'
    | '/features/mentorship'
    | '/features/risk'
    | '/api/public/stripe-webhook'
    | '/api/public/enroll/$applicationId'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApplyRoute: typeof ApplyRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  DiscordRoute: typeof DiscordRoute
  PrivacyRoute: typeof PrivacyRoute
  ProgramRoute: typeof ProgramRoute
  RefundRoute: typeof RefundRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SuccessRoute: typeof SuccessRoute
  TermsRoute: typeof TermsRoute
  TestCheckoutRoute: typeof TestCheckoutRoute
  BlogBreakoutStrategyRoute: typeof BlogBreakoutStrategyRoute
  FeaturesCommunityRoute: typeof FeaturesCommunityRoute
  FeaturesCurriculumRoute: typeof FeaturesCurriculumRoute
  FeaturesMentorshipRoute: typeof FeaturesMentorshipRoute
  FeaturesRiskRoute: typeof FeaturesRiskRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
  ApiPublicEnrollApplicationIdRoute: typeof ApiPublicEnrollApplicationIdRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-checkout': {
      id: '/test-checkout'
      path: '/test-checkout'
      fullPath: '/test-checkout'
      preLoaderRoute: typeof TestCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program': {
      id: '/program'
      path: '/program'
      fullPath: '/program'
      preLoaderRoute: typeof ProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discord': {
      id: '/discord'
      path: '/discord'
      fullPath: '/discord'
      preLoaderRoute: typeof DiscordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/risk': {
      id: '/features/risk'
      path: '/features/risk'
      fullPath: '/features/risk'
      preLoaderRoute: typeof FeaturesRiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/mentorship': {
      id: '/features/mentorship'
      path: '/features/mentorship'
      fullPath: '/features/mentorship'
      preLoaderRoute: typeof FeaturesMentorshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/curriculum': {
      id: '/features/curriculum'
      path: '/features/curriculum'
      fullPath: '/features/curriculum'
      preLoaderRoute: typeof FeaturesCurriculumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/community': {
      id: '/features/community'
      path: '/features/community'
      fullPath: '/features/community'
      preLoaderRoute: typeof FeaturesCommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/breakout-strategy': {
      id: '/blog/breakout-strategy'
      path: '/blog/breakout-strategy'
      fullPath: '/blog/breakout-strategy'
      preLoaderRoute: typeof BlogBreakoutStrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/enroll/$applicationId': {
      id: '/api/public/enroll/$applicationId'
      path: '/api/public/enroll/$applicationId'
      fullPath: '/api/public/enroll/$applicationId'
      preLoaderRoute: typeof ApiPublicEnrollApplicationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApplyRoute: ApplyRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  DiscordRoute: DiscordRoute,
  PrivacyRoute: PrivacyRoute,
  ProgramRoute: ProgramRoute,
  RefundRoute: RefundRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SuccessRoute: SuccessRoute,
  TermsRoute: TermsRoute,
  TestCheckoutRoute: TestCheckoutRoute,
  BlogBreakoutStrategyRoute: BlogBreakoutStrategyRoute,
  FeaturesCommunityRoute: FeaturesCommunityRoute,
  FeaturesCurriculumRoute: FeaturesCurriculumRoute,
  FeaturesMentorshipRoute: FeaturesMentorshipRoute,
  FeaturesRiskRoute: FeaturesRiskRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
  ApiPublicEnrollApplicationIdRoute: ApiPublicEnrollApplicationIdRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
