// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ugnyssxvtwvbbckycmru.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVnbnlzc3h2dHd2YmJja3ljbXJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODkzNDYyMDksImV4cCI6MjEwNDkyMjIwOX0.d5ZthlUj0Xmd1puZ3lM0cXjbk_CQDuZvO38cpxIVWpE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});